from typing import Any, Optional, List

class ChatGoogleGenerativeAI:
    def __init__(self, model: str = ..., google_api_key: Optional[str] = ..., temperature: Optional[float] = ...) -> None: ...
    def with_structured_output(self, model_type: Any) -> Any: ...
    def invoke(self, messages: Any) -> Any: ...

__all__ = ["ChatGoogleGenerativeAI"]
